<a href="https://colab.research.google.com/github/khatrisnk/learn-python/blob/main/Python_Crash_Course_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Python Crash Course 3

**AGENDA**

**- Recap**


**- Numpy Arrays**

- Create NumPy arrays
- Convert lists and tuples to NumPy arrays
- Inspect the structure and content of arrays
- Subset, slicing, indexing and iterate through arrays
- Arithmetic Operations

**- Pandas dataframe**

- Basics of Pandas
- Reading data
- Some basic operations on pandas dataframe

**- Two ungraded assignments**

### NUMPY Arrays

In [ ]:
import numpy as np

In [ ]:
# Creating numpy arrays

In [ ]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [ ]:
print(a1D)

[1 2 3 4]


In [ ]:
print(a2D)

[[1 2]
 [3 4]]


In [ ]:
print(a3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
print(f"1. {np.arange(10)}")

print(f"2. {np.arange(2, 10, dtype=float)}")

print(f"3. {np.arange(2, 3, 0.1)}")

1. [0 1 2 3 4 5 6 7 8 9]
2. [2. 3. 4. 5. 6. 7. 8. 9.]
3. [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [ ]:
# Zeroes and Ones

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.diag(np.full(4,1))

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
# Convert lists and tuples to NumPy arrays

In [ ]:
num_list = [1, 3, 5]
print(type(num_list))

print(type(np.array(num_list)))
np.array(num_list)

<class 'list'>
<class 'numpy.ndarray'>


array([1, 3, 5])

In [ ]:
tuple_list = (1,2,3)
print(type(tuple_list))
print(type(np.array(tuple_list)))
np.array(tuple_list)

<class 'tuple'>
<class 'numpy.ndarray'>


array([1, 2, 3])

In [ ]:
# Inspect the structure and content of arrays

In [ ]:
# Inspecting shape of an array
print(a1D.shape)
print(a2D.shape)
print(a3D.shape)

(4,)
(2, 2)
(2, 2, 2)


In [ ]:
a1D.shape[-1]

4

In [ ]:
# inspecting length of an array
print(len(a1D))
print(len(a2D))
print(len(a3D))

4
2
2


In [ ]:
# Reshape operation
print(np.arange(20))
a = np.arange(20).reshape((4,5))
print(a.shape)
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(4, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [ ]:
a.reshape?

In [ ]:
b = a.reshape((5,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
a.reshape((-1,a.shape[0]))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
a.reshape((a.shape[0], -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [ ]:
a1D.shape

(4,)

In [ ]:
a1D.reshape((-1,1)) # change row vector to column vector

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
a = np.ones((1, 2, 3))
a.shape

(1, 2, 3)

In [ ]:
print(num_list)
print(np.array(num_list)[-1])

[1, 3, 5]
5


In [ ]:
print(num_list[1])

3


In [ ]:
print(num_list[1:])

[3, 5]


In [ ]:
new_list = np.array([1, 2, 3, 4, 5, 6])
print(new_list[2:5])

[3 4 5]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In [ ]:
# Element-wise multiplication
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [ ]:
# Broadcasting
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [ ]:
# Broadcasting rules
'''
Two dimensions are compatible when

- they are equal, or

- one of them is 1.
'''

In [ ]:
# Iterating in array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

for x in arr:
  print(x)
  for y in x:
    print(y)

(2, 3)
[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [ ]:
# Array concatenation
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
# Splitting arrays
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# search in array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0) # all elements at "even position"

print(x)

(array([1, 3, 5, 7]),)


### PANDAS DataFrame

In [ ]:
import pandas as pd

In [ ]:
# Creating dataframes
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

col1  col2
0     1     3
1     2     4

In [ ]:
# Checking datatype of elements
df.dtypes

col1    int64
col2    int64
dtype: object

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
# Constructing dataframe from numpy arrays
df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                   columns=['a', 'b', 'c'])
df2

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
# Reading a CSV file from a URL
df = pd.read_csv('https://raw.githubusercontent.com/scpike/us-state-county-zip/master/geo-data.csv')

In [ ]:
df.head()

state_fips    state state_abbr zipcode      county        city
0           1  Alabama         AL   35004   St. Clair       Acmar
1           1  Alabama         AL   35005   Jefferson  Adamsville
2           1  Alabama         AL   35006   Jefferson       Adger
3           1  Alabama         AL   35007      Shelby    Keystone
4           1  Alabama         AL   35010  Tallapoosa    New site

In [ ]:
df.shape

(33103, 6)

In [ ]:
len(df)

33103

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33103 entries, 0 to 33102
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   state_fips  33103 non-null  int64 
 1   state       33103 non-null  object
 2   state_abbr  33103 non-null  object
 3   zipcode     33103 non-null  object
 4   county      33103 non-null  object
 5   city        33044 non-null  object
dtypes: int64(1), object(5)
memory usage: 1.5+ MB


In [ ]:
df.describe()

state_fips
count  33103.000000
mean      29.780533
std       15.291582
min        1.000000
25%       18.000000
50%       29.000000
75%       42.000000
max       56.000000

In [ ]:
df['state'].nunique()

51

In [ ]:
df['state'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New hampshire',
       'New jersey', 'New mexico', 'New york', 'North carolina',
       'North dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode island', 'South carolina', 'South dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West virginia', 'Wisconsin', 'Wyoming'], dtype=object)

### Ungraded Assignments

1. Create a numpy array from the CSV dataset which should contain the top 10 states having the maximum number of zipcodes. Example, is StateA has 3 zipcodes, StateB has 8 zipcodes and StateC has 2 zipcodes, the output should be ["StateB", "StateA". "StateC"]
2. Create a dataframe with State names and count of zipcodes as the columns and sort the dataframe in ascending order