<a href="https://colab.research.google.com/github/khatrisnk/learn-python/blob/main/Python_Crash_Course_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Python Crash Course 1

**AGENDA**
- Introduction to Jupyter notebooks for Python
- Basic Syntax and Operation in Python
- Data Structures in Python
- Control Structures and functions in Python

### Basic Syntax and Opertaions in Python

In [ ]:
# Basic arithmetic operations such as +, -, *, %, **
a = 5 + 10
b = 19 - 6
c = 61 * 2
d = 45 / 9
e = 12 % 10
f = 3 ** 3

In [ ]:
# print -- inline comment
'''
Let's try differnt types of comments
-> This is example of multi line or block comments
'''
print(a)
print(f"The value of b is {b}, c is {c}, d is {d}")
print("The values of e and f are {} and {} respectively".format(e, f))

15
The value of b is 13, c is 122, d is 5.0
The values of e and f are 2 and 27 respectively


In [ ]:
str_var = "Now, this is a string variable"
print(str_var)
bool_var = True
complex_var = 10 + 2j

Now, this is a string variable


In [ ]:
"""
Let's see basic data types in Python
"""
print(f"Type of variable a is: {type(a)}")
print(f"Type of variable d is: {type(d)}")
print(f"Type of variable str is: {type(str_var)}")
print(f"Type of variable (e,f) is: {type((e,f))}")
print(f"Type of variable bool_var is: {type(bool_var)}")
print(f"Type of variable complex_var is: {type(complex_var)}")

Type of variable a is: <class 'int'>
Type of variable d is: <class 'float'>
Type of variable str is: <class 'str'>
Type of variable (e,f) is: <class 'tuple'>
Type of variable bool_var is: <class 'bool'>
Type of variable complex_var is: <class 'complex'>


In [ ]:
# Taking input in Python
name = input("Enter your first name: ")
print("Hey! " + name)

Enter your first name: Adi
Hey! Adi


In [ ]:
age = int(input("Enter your age: "))
new = str(age + 1)
name = input("Enter your name: ")
print("Hey! " + name + " Next year you will be " + new)

Enter your age: 30
Enter your name: Ram
Hey! Ram Next year you will be 31


### Data Structures in Python

In [ ]:
# This is a list
new_list = [1, 2, "string"]
print(type(new_list))

<class 'list'>


In [ ]:
# This is a tuple
new_tuple = (0, "string")
print(type(new_tuple))

<class 'tuple'>


In [ ]:
# This is a dictionary
new_dict = { 1 : "Value1",
             2 : "Value2",
             3 : "Value3"
           }
print(new_dict)
print(type(new_dict))           

{1: 'Value1', 2: 'Value2', 3: 'Value3'}
<class 'dict'>


In [ ]:
# This is a set
setA = set([1, 1, 4, 4, 4, 9, 9, 16, 25, 25, 25])
print(setA)
print(type(setA))

{1, 4, 9, 16, 25}
<class 'set'>


### Control Structures and functions in Python

In [ ]:
# if-elif-else
score = 85
grade = None
print(type(None))

if score >= 80:
  grade = 'A'
elif score >= 60:
  grade = 'B'
elif score >= 40:
  grade = 'C'
else:
  grade = 'F'

print(grade)

<class 'NoneType'>
A


In [ ]:
# loops
# for loops
age = 20

for age in range(18, 25):
  print(age)


18
19
20
21
22
23
24


In [ ]:
vowels = ['a', 'e', 'i', 'o', 'u']
text = "Hello"
vowel_counter = 0

for ch in text:
  if ch in vowels:
    vowel_counter += 1

print(vowel_counter)

2


In [ ]:
# while loops
a = 8
while (a > 5):
  print(f"{a} is greater than 5")
  a -= 1

8 is greater than 5
7 is greater than 5
6 is greater than 5


In [ ]:
# List comprehension
num_list = [1, 2, 3, 7]
cube_list = [i**3 for i in num_list]
print(cube_list)

# conditionals in list comprehensions
even_cubes = [i**3 for i in num_list if i%2 == 0]
print(even_cubes)

sq_cubes = [i**3 if i%2==0 else i**2 for i in num_list]
print(sq_cubes)

[1, 8, 27, 343]
[8]
[1, 8, 9, 49]


In [ ]:
# Functions
def my_func(i):
  if i%2 == 0:
    return i**3
  else:
    return i**2

for i in num_list:
  print(my_func(i))

1
8
9
49


In [ ]:
# Lambda functions - is an anonymous function, which means that it is a function without a name. 
transform_x = lambda x : x**3 if(x%2 == 0) else x**2

for i in num_list:
  print(transform_x(i))

1
8
9
49


In [ ]:
# Map, Filter, Reduce
"""
Map is a function that works like list comprehensions and for loops. 
It is used when you need to map or implement functions 
on various elements at the same time.
"""
print("Transforming num_list using map function : ", end="")
print(list(map(transform_x, num_list)))


"""
Filter is a similar operation, but it requires the function to look for a condition 
and then, only returns those elements from the collection that satisfy the condition. 
"""
print("Extracting odd elements using filter : ", end="")
print(list(filter(lambda x: x%2 !=0, num_list)))

"""
'Reduce' is an operation that breaks down the entire process 
into pair-wise operations 
and uses the result from each operation, with the successive element.
"""
from functools import reduce

# using reduce to compute maximum element from list
print("The maximum element of the list is : ", end="")
print(reduce(lambda a, b: a if a > b else b, num_list))

Transforming num_list using map function : [1, 8, 9, 49]
Extracting odd elements using filter : [1, 3, 7]
The maximum element of the list is : 7


### Ungraded Assignments
1. Python program to print Fibonacci series of any input 'n'
2. Python program to check if a string is Palindrome or not

In [ ]:
class Airthmetics:
    def add(self, a,b):
        return a+b
    
    def multiplication(self, a,b):
        return a*b
    

arth = Airthmetics()
arth.add(2,3)

5

In [ ]:
import numpy as np

In [ ]:
np.diag([1,1])

array([[1, 0],
       [0, 1]])

In [ ]:
np.ones((1, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.ones((1, 1, 1))

array([[[1.]]])

In [ ]:
?np.full

In [ ]:
a = np.arange(20).reshape((4,5))

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a.reshape((0, len(a)))

ValueError: cannot reshape array of size 20 into shape (0,4)

In [ ]:
a.reshape((a.shape[1], a.shape(0)))

TypeError: 'tuple' object is not callable

In [ ]:
x = a.shape[0]

In [ ]:
y = a.shape[1]

In [ ]:
x = a.shape[0]
y = a.shape[1]
a.reshape((y,x))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
a.reshape([x,y])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a.reshape((-1,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [ ]:
a = np.array([1,2,3])
b = np.array([2,2,(2,4)])
a*b

/var/folders/7_/8px52ys552g8ncjsx6czydyh0000gn/T/ipykernel_17407/2035960674.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b = np.array([2,2,(2,4)])


array([2, 4, (2, 4, 2, 4, 2, 4)], dtype=object)